#ifndef KEYPOINT_PLUGIN_GLOBAL_H
#define KEYPOINT_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KEYPOINT_PLUGIN_LIBRARY)
#  define KEYPOINT_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define KEYPOINT_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KEYPOINT_PLUGIN_GLOBAL_H
