#ifndef FOURIER_PLUGIN_GLOBAL_H
#define FOURIER_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FOURIER_PLUGIN_LIBRARY)
#  define FOURIER_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FOURIER_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FOURIER_PLUGIN_GLOBAL_H
