#ifndef TEMPLATE_PLUGIN_GLOBAL_H
#define TEMPLATE_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPLATE_PLUGIN_LIBRARY)
#  define TEMPLATE_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPLATE_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLATE_PLUGIN_GLOBAL_H
